### ISSUE TITLE
Branch SDK should be able to tell whether it's running on Debug or Release build

### ISSUE THREAD

**Issue by arielelkin** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#171]
It's currently possible to release an app with just Branch test keys.

This SDK should prevent developers from committing that mistake.

It really should be the responsibility of the Branch SDK to know whether it’s running on a debug or release version of the app. It can use things such as preprocessor macros or environmental variables to be able to determine that. 

Then developers would only need a single Branch key!

**Comment by dickverbunt** [comment]
+1 👍🏼

**Comment by shortstuffsushi** [comment]
I'm curious, how do ou propose this be done at compile time? Short of adding a script to the Build Phases, I don't know how we would determine that. We do log a warning about it if we find that you're using a test key when the app is running.

**Comment by shortstuffsushi** [comment]
Unless you're specifically referring to the getTesdInstance method. We could make that available via pragma, but what would we pragma on, whether the DEBUG constant was available? That constant isn't present for all devs, so that would be an incomplete solution at best.

**Comment by arielelkin** [comment]
Apple does include a `DEBUG` compiler preprocessor flag in debug builds. You can then do something like:

```
#ifdef DEBUG
//use Branch test key
#else
//use Branch live key
#endif
```

More info here: http://stackoverflow.com/q/9063100/1072846

This flag is present by default in Xcode, but it wouldn't matter for the Branch SDK if I were to turn it off, as the Branch SDK is compiled and built according to its own scheme. 

Environmental variables are a good alternative:
http://stackoverflow.com/a/24344459/1072846

**Comment by shortstuffsushi** [comment]
The `DEBUG` macro is indeed present by default, but not a value that can be relied on, since it isn't a built in feature, it's just a default project template nicety. Relying on that makes me nervous.

We also can't control environment variables, those have to be defined per project, and we can't influence them, or guess which values will be present.

We also can't build the framework without it. In the literal sense, we could, but we don't want to offer two separate files for this, as that would just end up leading to more support issues for us.

I think typically we recommend this be done at the project level, since you control your own project and can put these sorts of guards in place. We can't rely on these projects having these items present, though. We could put these sorts of guards in place, but it still wouldn't resolve all cases, and would probably just make things more messy from a coding perspective.

One additional concern I have is for users who create beta builds, which require a release mode build. In this scenario, we would be blocking them from releasing those builds in test mode, which also isn't ideal.

**Comment by arielelkin** [comment]
>The DEBUG macro is indeed present by default, but not a value that can be relied on, since it isn't a built in feature, it's just a default project template nicety. Relying on that makes me nervous.

Sorry but that's wrong, it's not volatile thing. `#define` preprocessor commands are a safe way to conditionally compile code, and Apple does guarantee the stability of the `DEBUG` macro:
https://developer.apple.com/library/mac/technotes/tn2347/_index.html
https://developer.apple.com/library/prerelease/watchos/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingIvarsAndTypes.html

> We also can't control environment variables, those have to be defined per project, and we can't influence them, or guess which values will be present.

Yes, you can control environment variables. You can see for yourself here: http://stackoverflow.com/a/24344459/1072846

May I suggest you take a look at how Parse does it:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/

**Comment by shortstuffsushi** [comment]
Perhaps I'm not following what you're saying, but the [tech note link](https://developer.apple.com/library/mac/technotes/tn2347/_index.html#//apple_ref/doc/uid/DTS40014516-CH1-THE_DEBUG_PREPROCESSOR_MACRO-THE_DEBUG_PREPROCESSOR_MACRO_IN_XCODE) you sent mentions specifically what I said: `The preprocessor "DEBUG" macro is defined in all Xcode project templates for debug builds.` However, this value *can* be removed from the `Preprocesser Macros` section of the build settings, and in fact, a bug in Cocoapods caused this behavior for a while (though I can't seem to find the issue now). In this case (the case where `DEBUG=1` had been removed), the developer would never have the `getTestInstance` method available, and would likely come to use requesting help.

I'm also not understanding what you mean about the environment variables. Yes, it is possible to define them at a project level, but Branch doesn't have project level controls like that (we're just a drop into your existing project), so you would have to define those environment variables in your project. Sure, we could include them in *our* project that exports the library (for users who use the Framework file as opposed to Cocoapods), but as I stated before, we don't want to do this because it would require us to create two builds (a release and debug version).

I looked at Parse's use of both [`ifdef`](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/search?utf8=%E2%9C%93&q=ifdef&type=Code) and [`ifndef`](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/search?utf8=%E2%9C%93&q=ifndef&type=Code), and wasn't able to find anything about debug vs release builds. Could you point me to a portion of that SDK that you think would be useful to demonstrate this? Parse defines some constants that they utilize internally, but I don't see them enabling or disabling functionality depending on the build type. Please let me know if I'm missing where they do this.

**Comment by francisjervis** [comment]
Correct, Parse has a “developer” and “production” flag that can be set in their dashboard, but this is not detected automatically.

**Comment by arielelkin** [comment]
Regarding preprocessor macros: 

In the case of the Framework file: sure: you don't have any guarantees that the user project's preprocessor macros won't be tampered with, but that won't affect the preprocessor macros used to build just the branch library. In other words, if you set the `DEBUG` macro on the branch xcode project that builds the branch library, then drag and drop it into a new xcode project from which you remove the `DEBUG` macro, Branch's macros are unaffected. 

In the case of cocoapods: you simply have to define those macros on the podspec:
https://guides.cocoapods.org/syntax/podspec.html#compiler_flags
