### ISSUE TITLE
dyld: Library not loaded CoreSpotlight.framework

### ISSUE THREAD

**Issue by vandutran** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#226]
Got this error:

`dyld: Library not loaded: /System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight
  Referenced from: /private/var/mobile/Containers/Bundle/Application/01D565EC-548D-4CB7-AE85-AE736200D50C/X.app/X
  Reason: image not found`

Xcode 7.1.1, Swift 2.1, deployment target iOS 8.0

**Comment by Sarkar** [comment]
@vandutran ack - what version of the SDK are you using? Our latest released make CoreSpotlight weakly linked, so that if you deploy on iOS < 9, this shouldn't occur. If you're not on the latest, please upgrade to the latest.

If you're on the latest, can you ensure that your own project doesn't mark CoreSpotlight as 'required' when you're deploying to iOS 8.x?

**Comment by vandutran** [comment]
Was on 0.11.8 but ok solved with making CoreSpotlight optional.
