### ISSUE TITLE
Allow switching instance?

### ISSUE THREAD

**Issue by DimaVartanian** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#236]
Our prerelease/beta apps give users the ability to switch between a staging and production environment while the app is running. We have a separate Branch project set up for each one of these. The problem I'm having is that repeated calls to `initSessionWithLaunchOptions...` (with getInstance and getTestInstance swapped in depending on which one is correct) seem to not do anything. No matter what, only the initial handler seems to ever get called (which when opening a link meant for the wrong environment just gives blank params). Is there a correct way to change environments and register a new handler in order to switch from one environment to the other?

**Comment by derrickstaten** [comment]
@DimaVartanian are you wanting to switch between live and test keys mid-session? That's not something we support, and we're unlikely to support it unfortunately. 

You could build in a toggle that allows users to change the key for next app launch. You could store "shouldUseTestKey": YES or NO in NSUserDefaults. Then users could kill the app. The next time they opened the app, if "shouldUseTestKey" is true, then you could invoke `getTestInstance` instead of `getInstance`. 

Does this make sense?

**Comment by DimaVartanian** [comment]
Hi Derrick. That is indeed what I want since the users are able to change environments on the fly in our beta builds. I'll just force an app restart after doing that. Thanks!
