### ISSUE TITLE
Calling registerView in viewDidAppear on First Launch May Cause UI Issues

### ISSUE THREAD

**Issue by Adlai-Holler** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#265]
If I call `branchUniversalObject.registerView()` in `viewDidAppear` after calling super, on first launch of my app, my status bar style is permanently switched to black, I get warnings from `NSKeyedArchiver` about duplicate keys such as `UIHasPattern` and `UIRenderingMode`, and sometimes I get a UIKit warning about `Unbalanced calls to begin/end appearance transitions for <UIViewController: 0xblahblah>`. Nothing else happens, no view controller is presented or anything. 

I'm in release prep, or else I'd try to help with debugging, but I wanted to get visibility around this issue.

**Comment by derrickstaten** [comment]
@Adlai-Holler this is likely due to cookie-based matching, where we use an invisible SFSafariViewController. What version of the SDK are you using? If you're on `0.11.12`, please upgrade to `0.11.13` to see if you're still experiencing issues.

You can also disable cookie-based matching completely by invoking [disableCookieBasedMatching](https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/Branch.h#L459). 

Please let us know if you're still experiencing this on `0.11.13`. cc @joshuafeldman

**Comment by Adlai-Holler** [comment]
Ah! Yeah 0.11.13 fixes it. Thanks for the quick response!

**Comment by derrickstaten** [comment]
Excellent! @joshuafeldman thanks again for the fix here. Awesome work.

**Comment by joshuafeldman** [comment]
@derrickstaten always a pleasure!
