### ISSUE TITLE
Branch links generated from the Android SDK are not working when opening on iOS without the application installed

### ISSUE THREAD

**Issue by joshuafeldman** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#287]
We just started debugging this issue, but I thought it would be a good idea to create a ticket in case it is a known issue or guidance can be provided.

Basically our Android client is generating the link through the Branch SDK and texting it to an iOS device. We tap the link on the iOS device expecting it to route to the App Store but Safari just displays an error (most likely in the redirect). A link generated from the iOS SDK works correctly and opens the App Store.

![img_0075](https://cloud.githubusercontent.com/assets/753652/12937730/62243dc0-cf60-11e5-9ed3-16a5139b2412.PNG)

**Comment by joshuafeldman** [comment]
@derrickstaten if you're around we could use some insight. Thanks!

**Comment by derrickstaten** [comment]
@joshuafeldman can you tell me:

1. what is the link
2. what OS version you're on

this isn't really an iOS SDK issue, so it may be best discussed via support@branch.io

**Comment by joshuafeldman** [comment]
@derrickstaten the link is http://dl.flipagram.com/mnnh/Y6T2wBcgQq which is generated through our Android client. Maybe if you can tell me what might be wrong with the link it will help me debug it.

**Comment by joshuafeldman** [comment]
Maybe I should have opened the ticket in the Android repository

**Comment by derrickstaten** [comment]
@joshuafeldman it's your $ios_url -- that's supposed to be an HTTP url that we fall back to when the app is *not* installed. This should definitely not be a URI like `myapp://deeplink-path`.

--

In order to open the app when it is installed, you'll need to set up Universal Links. As of iOS 9.2, there is no longer a way to try to open the app via URI, then fall back to the App Store. So we've recommended that all partners move over to Universal Links.

We have a blog post about the change here: https://blog.branch.io/ios-9.2-redirection-update-uri-scheme-and-universal-links

We have a guide to setting up Universal Links here: https://dev.branch.io/recipes/branch_universal_links/ios/

**Comment by joshuafeldman** [comment]
@derrickstaten turns out the Android client was actually overriding the App Store URL to a deep link which was causing the issue. Thanks.
