### ISSUE TITLE
Add a way to disable console logging

### ISSUE THREAD

**Issue by milancermak** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#351]
I'd like a way how to disable debug and warning output from the console log:
```
2016-05-19 15:46:23.038 8fit Debug[26445:3229567] [Branch Warning] You are using your test app's Branch Key. Remember to change it to live Branch Key for deployment.
2016-05-19 15:46:23.039 8fit Debug[26445:3229567] [Branch Warning] Cannot use cookie-based matching while setDebug is enabled
2016-05-19 15:46:23.043 8fit Debug[26445:3229567] [BNCServerInterface.m:196] using url = https://api.branch.io/v1/open
```

Since there's no way how to do that directly on the `Branch` class, I wanted to set `debug` and `suppressWarningLogs` on the `BNCPreferenceHelper` singleton. However I'm using it in a swift project and because of the [unique way](http://stackoverflow.com/a/35004679/1370986) how Swift interoperates with ObjC, I can't call the `preferenceHelper` class method to get the singleton instance.

Can you please add a way how to disable this console output?

**Comment by ahmednawar** [comment]
@milancermak both methods should be called from your Branch instance.
`suppressWarningLogs` (https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/Branch.h#L422) and `setDebug` (https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/Branch.h#L370)

`setDebug` is not called by default as well so you you could just remove it from your code and you won't see the debugging logs. You shouldn't need to call `BNCPreferenceHelper` since it is intended for internal use.

**Comment by milancermak** [comment]
That cleared it up for me. Cheers!
